from __future__ import annotations

import base64
import json
import textwrap
from dataclasses import dataclass
from typing import Any

import autogen

from app.config import get_settings
from app.llm_config import build_llm_config
from app.services.cadquery_parser import execute_cadquery


SYSTEM_PROMPT = """
You write valid CadQuery Python code that defines a part hierarchy.

Return JSON with this exact schema:
{
  "cadquery_code": "python source",
  "components": [
    {
      "node_id": "root",
      "name": "Readable component name",
      "kind": "assembly|part|feature",
      "parent_node_id": null,
      "color_hint": "#hex or null",
      "metadata": {"notes": "short explanation"}
    }
  ],
  "summary": "single sentence"
}

Rules:
- Code must assign the final CadQuery geometry to a variable named `result_model`.
- Use only CadQuery via the injected `cq` symbol and keep the script executable as plain Python.
- Prefer simple primitives and boolean operations over advanced OCC internals.
- Apply feature operations like `hole`, `cboreHole`, and `cskHole` from a workplane attached to an existing solid face, for example `base.faces(\">Z\").workplane().hole(8)`.
- If multiple logical parts exist, create intermediate variables for them.
- Components must reflect a tree rooted at `root`.
- Return only JSON.
""".strip()


FALLBACK_TEMPLATE = textwrap.dedent(
    """
    import cadquery as cq

    base = cq.Workplane("XY").box(60, 40, 12)
    boss = cq.Workplane("XY").center(0, 0).workplane(offset=6).cylinder(18, 8)
    body = base.union(boss)
    result_model = body.faces(">Z").workplane().hole(8)
    """
).strip()


@dataclass
class AgentOutput:
    cadquery_code: str
    components: list[dict[str, Any]]
    summary: str
    model_used: str
    used_fallback: bool = False


class CadQueryAgentService:
    def __init__(self) -> None:
        self.settings = get_settings()

    def generate(self, prompt: str, image_bytes: bytes | None = None, image_mime: str | None = None) -> AgentOutput:
        try:
            # Build LLM config based on configured provider
            llm_config = build_llm_config(self.settings)
            model_used = (
                self.settings.openai_model
                if self.settings.llm_provider == "openai"
                else self.settings.gemini_model
            )
        except (ValueError, AttributeError) as exc:
            return self._fallback(prompt, reason=f"LLM configuration error: {str(exc)}")

        try:
            message = self._build_prompt(prompt, image_bytes=image_bytes, image_mime=image_mime)
            agent = autogen.AssistantAgent(
                name="cadquery_designer",
                system_message=SYSTEM_PROMPT,
                llm_config=llm_config,
            )
            response = agent.generate_reply(messages=[{"role": "user", "content": message}])
            payload = self._parse_response(response)
            payload = self._validate_or_repair_payload(
                payload=payload,
                agent=agent,
                original_request=message,
            )
            return AgentOutput(
                cadquery_code=payload["cadquery_code"],
                components=self._normalize_components(payload.get("components", [])),
                summary=payload.get("summary", "Generated by AG2."),
                model_used=model_used,
            )
        except Exception as exc:
            return self._fallback(prompt, reason=str(exc))

    def _build_prompt(self, prompt: str, image_bytes: bytes | None, image_mime: str | None) -> str:
        parts = [f"User request:\n{prompt.strip()}"]
        if image_bytes:
            mime = image_mime or "image/png"
            encoded = base64.b64encode(image_bytes).decode("ascii")
            parts.append(
                "Reference image as data URL:\n"
                f"data:{mime};base64,{encoded}"
            )
        return "\n\n".join(parts)

    def _parse_response(self, response: Any) -> dict[str, Any]:
        if isinstance(response, dict):
            return response
        if not isinstance(response, str):
            raise TypeError("AG2 did not return a string response")
        cleaned = response.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.strip("`")
            if cleaned.startswith("json"):
                cleaned = cleaned[4:].strip()
        return json.loads(cleaned)

    def _validate_or_repair_payload(
        self,
        payload: dict[str, Any],
        agent: autogen.AssistantAgent,
        original_request: str,
    ) -> dict[str, Any]:
        code = payload.get("cadquery_code")
        if not isinstance(code, str) or not code.strip():
            raise ValueError("AG2 payload did not contain cadquery_code")

        try:
            execute_cadquery(code)
            return payload
        except Exception as exc:
            repair_prompt = textwrap.dedent(
                f"""
                The previous CadQuery code failed execution.

                Original request:
                {original_request}

                Previous JSON payload:
                {json.dumps(payload, indent=2)}

                Execution error:
                {type(exc).__name__}: {exc}

                Rewrite the response and return JSON only.
                Keep the same schema and ensure the final model is assigned to `result_model`.
                If you add holes or cut features, attach them to an existing solid face/workplane instead of calling `.hole()` on a fresh empty workplane.
                """
            ).strip()
            repaired_response = agent.generate_reply(
                messages=[{"role": "user", "content": repair_prompt}]
            )
            repaired_payload = self._parse_response(repaired_response)
            repaired_code = repaired_payload.get("cadquery_code")
            if not isinstance(repaired_code, str) or not repaired_code.strip():
                raise ValueError("Repair payload did not contain cadquery_code")
            execute_cadquery(repaired_code)
            return repaired_payload

    def _normalize_components(self, components: list[dict[str, Any]]) -> list[dict[str, Any]]:
        normalized: list[dict[str, Any]] = []
        for index, component in enumerate(components):
            normalized.append(
                {
                    "node_id": component.get("node_id") or f"node-{index}",
                    "name": component.get("name") or f"Component {index + 1}",
                    "kind": component.get("kind") or "part",
                    "parent_node_id": component.get("parent_node_id"),
                    "depth": int(component.get("depth") or 0),
                    "order_index": index,
                    "color_hint": component.get("color_hint"),
                    "metadata": component.get("metadata") or {},
                }
            )
        if not normalized:
            normalized = self._fallback_components()
        if normalized[0]["node_id"] != "root":
            normalized.insert(0, self._fallback_components()[0])
        return normalized

    def _fallback(self, prompt: str, reason: str) -> AgentOutput:
        summary = f"Fallback model used for: {prompt[:80]}" if prompt else "Fallback model used."
        components = self._fallback_components(reason=reason)
        return AgentOutput(
            cadquery_code=FALLBACK_TEMPLATE,
            components=components,
            summary=summary,
            model_used="fallback",
            used_fallback=True,
        )

    def _fallback_components(self, reason: str | None = None) -> list[dict[str, Any]]:
        return [
            {
                "node_id": "root",
                "name": "Generated Object",
                "kind": "assembly",
                "parent_node_id": None,
                "depth": 0,
                "order_index": 0,
                "color_hint": "#0f766e",
                "metadata": {"reason": reason} if reason else {},
            },
            {
                "node_id": "body",
                "name": "Main Body",
                "kind": "part",
                "parent_node_id": "root",
                "depth": 1,
                "order_index": 1,
                "color_hint": "#1d4ed8",
                "metadata": {"operation": "box"},
            },
            {
                "node_id": "boss",
                "name": "Top Boss",
                "kind": "feature",
                "parent_node_id": "root",
                "depth": 1,
                "order_index": 2,
                "color_hint": "#ea580c",
                "metadata": {"operation": "cylinder"},
            },
            {
                "node_id": "cutout",
                "name": "Center Hole",
                "kind": "feature",
                "parent_node_id": "root",
                "depth": 1,
                "order_index": 3,
                "color_hint": "#7c3aed",
                "metadata": {"operation": "hole"},
            },
        ]
